### ISSUE TITLE
Inline Code Highlighting

### ISSUE THREAD

**Issue by anatol-ju** [thorstenalpers/wp-plugin-code-block-for-elementor#1]
Hello Thorsten!
Your addon is great, I tried a few to include code highlighting, and so far I like yours the most.

However, there is one feature that I am missing and still have to use other addons for it: inline-formatting.

While it is great to have whole code blocks, I have to format short strings manually.
For example, if I want to include an array into the text, let's say [1,2,3], I have to use the <code></code> tags in the source code or mark and format with another tool.

You could, for example, use a short syntax like "<c>write code here</c>" or "/{ code here /}" in the text box.
This would save people lots of time!

Thank you in advance!

Kind regards.

**Comment by thorstenalpers** [comment]
Hi anatol-ju.
yes you are right, inline code highlighting is currently not possible with this plugin. Other plugins can do that.
This feature sounds interesting and could be easy to implement, but i have to take care about dark pages. So the theme must be configurable, maybe in the shortcode or in an extra admin area. I will look after it during this month.

Kind regards,
Thorsten

**Comment by thorstenalpers** [comment]
Sorry, currently I have no time to implement it,
