### ISSUE TITLE
Plugin not working with chrome

### ISSUE THREAD

**Issue by Ph4ntom01** [thorstenalpers/wp-plugin-code-block-for-elementor#2]
Hello thorstenalpers!

I find out that the parser is not working properly when I am using this configuration :

- All theme (except "Coy")
- Langages set : bash, sh
- All navigators based on chrome

Example when using any theme :
![Capture](https://user-images.githubusercontent.com/60856856/147353984-d6ca1ad0-eca9-4272-822d-bdde610145fc.PNG)

Example when using only the "Coy" theme :
![Capture2](https://user-images.githubusercontent.com/60856856/147353878-cd279e73-e07e-4c43-87c3-826ca3b24675.PNG)

It's working fine on Firefox.

Thank you in advance!

Kind regards.

**Comment by thorstenalpers** [comment]
For me it is working on Firefox and Chrome, maybe the bug is caused by an other activated wordpress plugin or by your Browser settings.


Theme: Okaidia
Language: Bash
![grafik](https://github.com/thorstenalpers/wp-plugin-code-block-for-elementor/assets/8270650/20b1ca1e-0020-450f-82bd-e268a57acdfc)
