### ISSUE TITLE
Plugin breaks with Elementor 3.16

### ISSUE THREAD

**Issue by skrubbeltrang** [thorstenalpers/wp-plugin-code-block-for-elementor#3]
The plugin seems to use deprecated functions.
Hopefully you'll find a few minutes to update it to be compatible with future versions of Elementor.
It's a very nice plugin.

https://developers.elementor.com/elementor-3-16-developers-update/
https://github.com/elementor/elementor/issues/23745

**Comment by rami-elementor** [comment]
I created a PR to fix the issue:

https://github.com/thorstenalpers/wp-plugin-code-block-for-elementor/pull/4

**Comment by thorstenalpers** [comment]
Thanks for contributing

**Comment by skrubbeltrang** [comment]
Fantastic! Awesome job 🙏🙏🙏
